In [1]:
!pip install numpy

In [16]:
import numpy as np

In [ ]:
a = [1,2,3,4,5]
print(a)
print(a[1:4])

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

In [24]:
a_mul = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.dtype)
print(a_mul.size)

(3, 3)
2
int32
9


In [29]:
a = np.array([[1,2,3],[4,"sea",6],[7,8,9]])
print(a[1,1])
print(type(a[1,1]))

sea
<class 'numpy.str_'>


In [32]:
d = {'1': 'A'}
a = np.array([[1,2,3],[4,d,6],[7,8,9]])
print(a[1,1])
print(a.dtype)

{'1': 'A'}
object


In [ ]:
a = np.full((3,4,5), 9)
print(a)

a = np.zeros((10,5,2))
print(a)
 
a = np.ones((2,3,4))
print(a)

In [45]:
x_values = np.arange(0, 200, 5)
print(x_values)
x_values = np.linspace(0, 1000, 4)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195]
[   0.          333.33333333  666.66666667 1000.        ]


In [51]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,0]

a1 = np.array(l1)
a2 = np.array(l2)

print(l1 * 5)
print(a1 * 5)

print(l1 + l2) #cant do this (/,*,-) except +
print(a1 + a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[ 7  9 11 13  5]


In [54]:
a1 = np.array([1,2,3])
a2 = np.array([[1],
              [2]])
print(a2.shape)
print(a1 + a2)

(2, 1)
[[2 3 4]
 [3 4 5]]


In [56]:
a = np.array([[10,100,1000],[4,5,6]])
print(np.log10(a))

[[1.         2.         3.        ]
 [0.60205999 0.69897    0.77815125]]


In [61]:
a = np.array([[10,100,1000],[4,5,6]])

a = np.append(a, [1,2,3])

a = np.insert(a, 6,[7,8])
print(a)

print(np.delete(a,2))
print(np.delete(a,3))

[  10  100 1000    4    5    6    7    8    1    2    3]
[ 10 100   4   5   6   7   8   1   2   3]
[  10  100 1000    5    6    7    8    1    2    3]


In [72]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
#print(a.shape)

#print(a.reshape((5,4)))
#print(a.reshape((2,5,2)))

print(a.flatten())
print(a.ravel())

var1 = a.flatten()
var1[2] = 100   
print(var1)
print(a)

var = [v for v in a.flat]
print(var)

print(a.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[  1   2 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[[ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]
 [ 5 10 15 20]]


In [77]:
a1 = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

a2 = np.array([[11,12,13,14,15],
              [16,17,18,19,20]])

a = np.concatenate((a1, a2), axis=0)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [79]:
a = np.array

print(np.split(a,4, axis=0))
print(a.min())
print(a.max())
print(a.mean())   
print(a.std())
print(np.median(a))

[array([[1, 2, 3, 4, 5]]), array([[ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15]]), array([[16, 17, 18, 19, 20]])]


In [80]:
numbers = np.random.randint(100, size=(2,3,4))
print(numbers)
numbers = np.random.choice([10,20,30], size=(2,3,4))

[[[16 37 74 96]
  [82 41  0 54]
  [58 61 52 44]]

 [[53 57 29 57]
  [36 90  4 75]
  [33 62 39 81]]]


In [81]:
np.save("mynumpy",a)